[api_resource_demo_be.util]
issuer = "https://dev.api.asgardeo.io/t/<tenant-name>/oauth2/token"
audience = "<client-id>"
jwksUrl = "https://dev.api.asgardeo.io/t/<tenant-name>/oauth2/jwks"
port = 3001

[api_resource_demo_be.util.issueScopes]
create = "issues:create"
view = "issues:view"